name: "42Crunch REST API Static Security Testing"

# Run workflow each time code is pushed to your repository
on: [push]

jobs:
  test-apis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 42Crunch REST API Static Security Testing
      uses: 42Crunch/api-security-audit-action@v1
      with:
        api-token: ${{ secrets.FORTY_TWO_CRUNCH_API_TOKEN}}
        # Fail if any OpenAPI file scores lower than 75
        min-score: 75
        # Upload results to Github code scanning
        upload-to-code-scanning: true
